# Generated by Django 4.0 on 2022-03-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('links', '0001_initial'), ('links', '0002_link_description_link_image_link_title')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('description', models.TextField(default='This is a descripton.', max_length=1000)),
                ('image', models.URLField(default='https://www.google.com')),
                ('title', models.TextField(default='This is a title.', max_length=200)),
            ],
        ),
    ]
