# Generated by Django 4.0 on 2022-02-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(
                default='This is a descripton.',
                max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.URLField(default='https://www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.TextField(default='This is a title.', max_length=200),
            preserve_default=False,
        ),
    ]
