# Generated by Django 4.0 on 2022-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_squashed_0002_link_description_link_image_link_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
