# Generated by Django 4.0 on 2022-01-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links_list', '0007_alter_linklist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linklist',
            old_name='user',
            new_name='owner',
        ),
    ]
