# Generated by Django 4.0 on 2022-01-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_list', '0008_rename_user_linklist_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linklist',
            name='links',
        ),
        migrations.AddField(
            model_name='linklist',
            name='links',
            field=models.ManyToManyField(related_name='linklists', to='links_list.Link'),
        ),
    ]
