# Generated by Django 4.0 on 2022-01-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links_list', '0010_alter_linklist_links_alter_linklist_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enlister',
        ),
    ]
