# Generated by Django 4.0 on 2022-01-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='link_list',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
