# Generated by Django 4.0 on 2022-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llists', '0001_squashed_0015_linklist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linklist',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
