# Generated by Django 4.0 on 2022-01-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('llists', '0002_rename_name_contact_link_list_remove_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='LinkList',
        ),
    ]
