# Generated by Django 4.0 on 2022-01-03 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llists', '0003_rename_contact_linklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='linklist',
            old_name='link_list',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Enlister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llists.link')),
                ('link_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llists.linklist')),
            ],
        ),
        migrations.AddField(
            model_name='linklist',
            name='links',
            field=models.ManyToManyField(through='llists.Enlister', to='llists.Link'),
        ),
    ]
