# Generated by Django 4.0 on 2022-01-04 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('llists', '0005_linklist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linklist',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='snippets',
                to='auth.user'),
        ),
    ]
