# Generated by Django 4.0 on 2022-01-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('llists', '0009_alter_linklist_links_delete_enlister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linklist',
            name='links',
        ),
        migrations.AddField(
            model_name='linklist',
            name='links',
            field=models.ManyToManyField(
                related_name='linklists',
                to='llists.Link'),
        ),
        migrations.AlterField(
            model_name='linklist',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='lists',
                to='auth.user'),
        ),
    ]
