# Generated by Django 4.0 on 2022-01-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('llists', '0011_delete_enlister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.AlterField(
            model_name='linklist',
            name='links',
            field=models.ManyToManyField(
                related_name='linklists',
                to='links.Link'),
        ),
    ]
