# Generated by Django 4.0 on 2022-01-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llists', '0012_delete_link_alter_linklist_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='linklist',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
