# Generated by Django 4.0 on 2022-02-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llists', '0013_linklist_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linklist',
            name='date',
        ),
    ]
