# Generated by Django 4.0 on 2022-02-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llists', '0014_remove_linklist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='linklist',
            name='description',
            field=models.CharField(
                default='This is a list description.',
                max_length=250),
            preserve_default=False,
        ),
    ]
