name: PR Linters Run

on: [ pull_request ]

jobs:
  run_js_linters:
    name: Run JS Linter Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install npm dependencies
      run: npm install eslint 
    - name: Install eslint standard
      run: npm install eslint-config-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node
    - name: Run eslint
      run: |
        npx eslint "**/*.js" --no-error-on-unmatched-pattern

  run_python_linters:
    name: Run Python Linter Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: pip install flake8==4.0.1
      - name: Run flake8
        run: flake8 --ignore F401,F811,E501